---
abstract: 'Install the PYX modules.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-PYX
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::PYX2XML: 0.01
  PYX: 0.04
  PYX::GraphViz: 0.04
  PYX::Hist: 0.04
  PYX::SGML::Raw: 0.02
  PYX::SGML::Tags: 0.01
  PYX::Sort: 0.03
  PYX::Stack: 0.04
  PYX::Utils: 0.04
  PYX::XMLNorm: 0.04
  PYX::XMLSchema::List: 0.04
  SGML::PYX: 0.02
  Tags::Output::PYX: 0.03
  XML::MinWriter: 0.08
  XML::PYX: 0.07
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-PYX
  homepage: https://github.com/tupinek/Task-PYX
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Task-PYX
version: '0.10'
